#!/usr/bin/env bash
#!/bin/bash

ETC_PATH=/etc/ductn
USER_BIN_PATH=~/bin
DIRTMP=/tmp/ductn

if [[ ! $BASH_SOURCE = /var/www/base/ductn ]] && [[ -f /var/www/base/ductn ]]; then
    source /var/www/base/ductn

    if [ -d /var/www/base/var/lib ]; then
        for f in /var/www/base/var/lib/*.sh; do
            [[ -f $f ]] && source $f
        done
    fi
    exit 0
else
    if [ -d /var/lib/ductn ]; then
        for f in /var/lib/ductn/*.sh; do
            [[ -f $f ]] && source $f
        done
    fi
fi

_init() {
    mkdir -p /tmp/ductn
    sudo chmod 777 -R /tmp/ductn

    --sys:service:install
}

_main() {
    --log:config

    --echo "Server\t\t$(--host:fullname)($(--host:address))"
    --echo "IP\t\t$(--ip:wan)"

    # read -t 5 -n 1 -s -r -p "Press any key to continue (5 seconds)"
    exit 0
}

[[ ! "$(whoami)" -eq "ductn" ]] && exit 1

_init

if [[ -n $* ]]; then
    "--$@"
else
    _main
fi

exit 0
