#!/usr/bin/env bash
#!/bin/bash

[[ $# -eq 0 ]] &&
    echo "No arguments supplied" &&
    exit 1

--commands() {
    declare -F | grep -- | awk '{print $3}' | cut -f3 -d':' | grep -v -e "^$" | awk '{print " - " $1}'
}

"--$@"
