#!/usr/bin/env bash
#!/bin/bash

[[ $# -eq 0 ]] &&
    echo "No arguments supplied" &&
    exit 1

--commands() {
    # echo "--commands"
    # declare -F | awk '{print $3}' | cut -f3 -d':' | grep -v -e "^$" | awk '{print " - " $1}'
    # declare -F | awk '{print $3}' | grep -e "^--"
    # declare -F | awk '{print $3}' | grep -e "^--" | awk '{print substr($1, 3, length($1))}'
    declare -F | awk '{print $3}' | grep -e "^--" | sed 's/--//g' | grep -v "commands"
}

[ ! -x "--$@" ] && echo "ductn: '$1' is not a ductn command." && exit 1

"--$@"
