#!/usr/bin/env bash
#!/bin/bash

_GLOBAL_EXEC=d_
_SRC=$(dirname $(realpath $0))

[[ $# -eq 0 ]] &&
    echo "No arguments supplied" &&
    exit 1

_LIB=/var/lib/ductn
[[ -d "$_SRC/var/lib" ]] &&
    _LIB="$_SRC/var/lib"
for file in $_LIB/*.sh; do
    [[ -f "$file" ]] &&
        [[ $(bash $file --isenabled) == '1' ]] &&
        source $file
done

d_commands() {
    declare -F | awk '{print $3}' | grep -e "^$_GLOBAL_EXEC" | sed "s/$_GLOBAL_EXEC//g" | grep -v "commands"
}

[[ (! -x "$_GLOBAL_EXEC$1") && (! $(type -t "$_GLOBAL_EXEC$1") == function) ]] && echo "'$1' is not a ductn command." && exit 1

"$_GLOBAL_EXEC$@"
