#!/usr/bin/env bash
#!/bin/bash

--apt:fix() {
    #!/bin/bash

    sudo killall apt-get
    sudo killall apt

    sudo rm /var/lib/apt/lists/lock
    sudo rm /var/cache/apt/archives/lock
    sudo rm /var/lib/dpkg/lock
    sudo rm /var/lib/dpkg/lock-frontend

    sudo dpkg --configure -a
}
