#!/bin/bash

DNS=false

--dns:update() {
    DNS="$(--ddns:getip dc2.diepxuan.com)"
    --dns:update:named

}

--dns:update:nameservers() {
    if [[ -f /etc/resolvconf/resolv.conf.d/base ]]; then
        echo "nameserver "$DNS"" | sudo tee /etc/resolvconf/resolv.conf.d/base > /dev/null
    fi
    sudo netplan set ethernets.ens192.nameservers.addresses=[1.1.1.1,8.8.8.8]
    sudo netplan apply
}

--dns:update:named() {
    echo "zone \"diepxuan.com\" {
    type slave;
    file \"db.diepxuan.com\";
    masters { "$DNS"; };
};
zone \"_msdcs.vswit.ch\" IN {
     type slave;
     file \"db._msdcs.diepxuan.com\";
     masters { "$DNS"; };
};" | sudo tee /etc/bind/named.conf.local > /dev/null
    sudo service named restart
}

--dns:server:install() {
    #!/bin/bash
    cd "$(dirname "$0")"

    # sudo apt install bind9 bind9utils bind9-doc dnsutils -y

    cat dns/slave.conf.options | ssh dx1.diepxuan.com "sudo tee /etc/bind/named.conf.options"
    cat dns/slave.conf.local | ssh dx1.diepxuan.com "sudo tee /etc/bind/named.conf.local"
    scp dns/db.* ductn@dx1.diepxuan.com
    ssh dx1.diepxuan.com "
            mkdir /etc/bind/zones
            sudo mv db.* /etc/bind/zones
            sudo service bind9 restart
        "

    cat dns/master.conf.options | ssh dx3.diepxuan.com "sudo tee /etc/bind/named.conf.options"
    cat dns/master.conf.local | ssh dx3.diepxuan.com "sudo tee /etc/bind/named.conf.local"
    scp dns/db.* ductn@dx3.diepxuan.com:~/
    ssh dx3.diepxuan.com "
            mkdir -p /etc/bind/zones
            sudo mv ~/db.* /etc/bind/zones
            sudo service bind9 restart
        "
    # sudo apt install stunnel4 -y --purge --auto-remove
    # cat /var/www/base/bash/dns/stunnel.conf | sudo tee /etc/stunnel/stunnel.conf
    # sudo service bind9 restart
}

