#!/bin/bash

NS1=false
NS2=false
DEV=0

--dns:init() {
    if [[ -z ${NS1+x} ]]; then return; else
        _ip="$(--ddns:getip dc1.diepxuan.com)"
        if [[ $_ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            NS1=$_ip
        else
            exit 1
        fi
    fi
    if [[ -z ${NS2+x} ]]; then return; else
        _ip="$(--ddns:getip dc2.diepxuan.com)"
        if [[ $_ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            NS2=$_ip
        else
            exit 1
        fi
    fi
}

--dns:update() {
    --dns:init

    if [[ -f /var/cache/bind/ns1.diepxuan.com ]] && [[ -f /var/cache/bind/ns2.diepxuan.com ]]; then
        if [[ "$NS1" =~ $(</var/cache/bind/ns1.diepxuan.com) ]] && [[ "$NS2" =~ $(</var/cache/bind/ns2.diepxuan.com) ]]; then
            echo ""
            if [[ $DEV -eq 0 ]]; then
                return 0
            fi
        else
            echo "$NS1" | sudo tee /var/cache/bind/ns1.diepxuan.com >/dev/null
            echo "$NS2" | sudo tee /var/cache/bind/ns2.diepxuan.com >/dev/null
        fi
    fi

    --dns:update:nameservers
    --dns:update:options
    --dns:update:named

    sudo systemd-resolve --flush-caches
    sudo rndc flush
    sudo rndc reload
    sudo service named restart
}

--dns:update:nameservers() {
    if [[ -f /etc/resolvconf/resolv.conf.d/base ]]; then
        echo "nameserver "$NS1"" | sudo tee /etc/resolvconf/resolv.conf.d/base >/dev/null
    fi
    sudo netplan set ethernets.ens192.nameservers.addresses=["$NS1","$NS2",1.1.1.1,8.8.8.8]
    sudo netplan apply
}

--dns:update:named() {
    _local="zone \"diepxuan.site\" {
    type slave;
    file \"/var/cache/bind/db.diepxuan.site\";
    masters {
        "$NS1";
        "$NS2";
    };
};"
    # echo $_local | sudo tee /etc/bind/named.conf.local >/dev/null
    echo "" | sudo tee /etc/bind/named.conf.local >/dev/null
}

--dns:update:options() {
    echo "options {
        directory \"/var/cache/bind\";
        forwarders {
            "$NS1";
            "$NS2";
            1.1.1.1;
            8.8.8.8;
        };
        forward only;
        dnssec-validation auto;

        allow-recursion { any; };
        recursion yes;

        auth-nxdomain no;
        allow-transfer { any; };

        listen-on-v6 { any; };

        masterfile-format text;
};" | sudo tee /etc/bind/named.conf.options >/dev/null
}

--dns:server:install() {
    #!/bin/bash
    cd "$(dirname "$0")"

    # sudo apt install bind9 bind9utils bind9-doc dnsutils -y

    # cat dns/slave.conf.options | ssh dx1.diepxuan.com "sudo tee /etc/bind/named.conf.options"
    # cat dns/slave.conf.local | ssh dx1.diepxuan.com "sudo tee /etc/bind/named.conf.local"
    # scp dns/db.* ductn@dx1.diepxuan.com
    # ssh dx1.diepxuan.com "
    #         mkdir /etc/bind/zones
    #         sudo mv db.* /etc/bind/zones
    #         sudo service bind9 restart
    #     "

    # cat dns/master.conf.options | ssh dx3.diepxuan.com "sudo tee /etc/bind/named.conf.options"
    # cat dns/master.conf.local | ssh dx3.diepxuan.com "sudo tee /etc/bind/named.conf.local"
    # scp dns/db.* ductn@dx3.diepxuan.com:~/
    # ssh dx3.diepxuan.com "
    #         mkdir -p /etc/bind/zones
    #         sudo mv ~/db.* /etc/bind/zones
    #         sudo service bind9 restart
    #     "

    # sudo apt install stunnel4 -y --purge --auto-remove
    # cat /var/www/base/bash/dns/stunnel.conf | sudo tee /etc/stunnel/stunnel.conf
    # sudo service bind9 restart
}
