#!/bin/bash

sudo add-apt-repository ppa:ondrej/php
sudo apt update
sudo apt install libapache2-mod-php?.? -y --purge --auto-remove
sudo update-alternatives --config php

#sudo update-alternatives --set php /usr/bin/php5.6
#sudo update-alternatives --set phar /usr/bin/phar5.6
#sudo update-alternatives --set phar.phar /usr/bin/phar.phar5.6
#sudo update-alternatives --set phpize /usr/bin/phpize5.6
#sudo update-alternatives --set php-config /usr/bin/php-config5.6


# INSTALL PHP MODULES
########################
sudo apt install phpmd -y --purge --auto-remove &>/dev/null
sudo apt install composer -y --purge --auto-remove &>/dev/null

sudo apt install -y libapache2-mod-php?.? php?.? php?.?-mysql php?.?-mbstring php?.?-mysqli php?.?-intl php?.?-curl php?.?-gd php?.?-mcrypt php?.?-soap php?.?-dom php?.?-xml php?.?-zip php?.?-bcmath php?.?-imagick &>/dev/null
sudo apt install -y php?.?-mongodb &>/dev/null
ductn_php_mssql
sudo service apache2 restart

