#!/usr/bin/env bash

_BASEDIR="/var/www/base"
_BASHDIR="$_BASEDIR/bash"

--install() {
    $_BASHDIR/ductn --swap --install
    sudo apt install -y --purge --auto-remove mysql-server
    # sudo mysql_secure_installation
}

--ssl:enable() {
    DIR=/etc/mysql/certs/

    mkdir $DIR
    # openssl genrsa 4096 | sudo tee ca-key.pem
    sudo cp $_BASHDIR/mysql/ssl/*.pem $DIR
    sudo openssl req -new -x509 -nodes -days 365000 -key $DIR/ca-key.pem -out $DIR/ca-cert.pem

    sudo openssl req -newkey rsa:2048 -days 365000 -nodes -keyout $DIR/server-key.pem -out $DIR/server-req.pem
    sudo openssl rsa -in $DIR/server-key.pem -out $DIR/server-key.pem
    sudo openssl x509 -req -in $DIR/server-req.pem -days 365000 -CA $DIR/ca-cert.pem -CAkey $DIR/ca-key.pem -set_serial 01 -out $DIR/server-cert.pem

    sudo openssl req -newkey rsa:2048 -days 365000 -nodes -keyout $DIR/client-key.pem -out $DIR/client-req.pem
    sudo openssl rsa -in $DIR/client-key.pem -out $DIR/client-key.pem
    sudo openssl x509 -req -in $DIR/client-req.pem -days 365000 -CA $DIR/ca-cert.pem -CAkey $DIR/ca-key.pem -set_serial 01 -out $DIR/client-cert.pem

    openssl verify -CAfile $DIR/ca-cert.pem $DIR/server-cert.pem $DIR/client-cert.pem
    cat $_BASHDIR/mysql/ssl/10-ssl.cnf | sudo tee /etc/mysql/conf.d/10-ssl.cnf

    sudo chown -R mysql:root $DIR
}

galera() {

    _MYSQL_GALERA="on"
    _MYSQL_GALERA_HOST=1

    while [ $# -gt 0 ]; do
        case $1 in
        -i | --install) _MYSQL_GALERA_TOOGLE="on" ;;
        --setup) _MYSQL_GALERA_SETUP="on" ;;
        --remove) _MYSQL_GALERA_TOOGLE="off" ;;
        --host=?* | -h=?*) _MYSQL_GALERA_HOST=${1#*=} ;;
        --host | -h)
            _MYSQL_GALERA_HOST=$2
            shift
            ;;
        --host=)
            die 'ERROR: "--host" requires a non-empty option argument.'
            ;;
        --) break ;;
        -?*) printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2 ;;
        *) break ;;
        esac

        shift
    done

}

"--$@"

F_mysql_galera() {

    --setup() {
        cd ~
        sudo add-apt-repository universe
        sudo apt install -y --purge --auto-remove software-properties-common apt-transport-https
        sudo add-apt-repository universe -r
        wget https://downloads.mariadb.com/MariaDB/mariadb_repo_setup -O mariasetup
        chmod +x mariasetup
        sudo ./mariasetup --mariadb-server-version="mariadb-10.3"
        sudo rm -rf ~/mariadb_repo_setup*
        sudo rm -rf ~/mariasetup*

        sudo apt update
        sudo apt install rsync mariadb-server mariadb-client
    }

    --install() {
        cd "$(dirname "$0")"

        cat $_BASHDIR/mysql_galera/mysqld.cnf | sudo tee /etc/mysql/conf.d/mysqld_cluster.cnf
        cat $_BASHDIR/mysql_galera/dx${_MYSQL_GALERA_HOST}.mysqld.cnf | sudo tee -a /etc/mysql/conf.d/mysqld_cluster.cnf

        sudo galera_new_cluster
        sudo service mysql restart
    }

    --remove() {
        sudo rm -rf /etc/mysql/conf.d/mysqld_cluster.cnf
        sudo rm -rf /etc/apt/sources.list.d/galera.list
        sudo rm -rf /etc/apt/preferences.d/galera.pref
    }

    $@
}

if [[ $_MYSQL_GALERA = "on" ]]; then
    if [[ $_MYSQL_GALERA_SETUP = "on" ]]; then
        F_mysql_galera --setup
    fi

    if [[ $_MYSQL_GALERA_TOOGLE = "on" ]]; then
        F_mysql_galera --install
    elif [[ $_MYSQL_GALERA_TOOGLE = "off" ]]; then
        F_mysql_galera --remove
    fi
fi
