#!/usr/bin/env bash

_BASEDIR="/var/www/base"
_BASHDIR="$_BASEDIR/bash"

service() {
    # Web Server
    if [[ ! "$(sudo /usr/sbin/service apache2 status)" =~ "start/running" ]]; then
        sudo /usr/sbin/service apache2 start
    fi
    if [[ ! "$(sudo /usr/sbin/service mysql status)" =~ "start/running" ]]; then
        $_BASHDIR/ductn --swap
        sudo /usr/sbin/service mysql start
    fi
    exit 0
}

--service() {
    service
}

if [ "$(whoami)" = "ductn" ]; then
    chmod u+x $_BASHDIR/cronjob/*.sh
    chmod u+x $_BASHDIR/cronjob/cronjob
    crontab $_BASHDIR/cronjob/cronjob.conf
fi

"--$@"

# sudo service cron restart
