#!/bin/bash

_IS_SERVER="off"
--server() {
    _IS_SERVER="on"
}

_IS_SUDOER="off"
--admin() {
    _IS_SUDOER="on"
}

$@

cd "$(dirname "$0")"
echo ". /var/www/base/bash/.bash_aliases" >~/.bash_aliases
rm ~/.vimrc
ln /var/www/base/bash/.vimrc ~/.vimrc
ln -s /var/www/base/bash/.vimrc ~/.vimrc
chmod 644 ~/.bash_aliases
chmod 644 ~/.vimrc
sed -i 's/.*force_color_prompt\=.*/force_color_prompt=yes/' ~/.bashrc

if [ "$(whoami)" = "ductn" ]; then
    chmod +x /var/www/base/bash/*
    sudo timedatectl set-timezone Asia/Ho_Chi_Minh
    sudo cp /var/www/base/bash/ductn /usr/local/bin/ductn
    sudo chown root:root /usr/local/bin/ductn
fi
./ductn --git -i

if [[ $_IS_SERVER = "on" ]]; then
    cd "$(dirname "$0")"
    ./ductn --cronjob -i
    ./ductn --httpd --config
    ./ductn --ssh -i
    # ./bash/ductn --update allowip
    # else
    # sudo mkdir -p /etc/auto.master.d/
    # echo "/dxvn /etc/auto.master.d/dxvn.sshfs --timeout=30" | sudo tee /etc/auto.master.d/dxvn.autofs
    # echo "luong -fstype=nfs,rw,soft,intr,IdentityFile=/home/ductn/.ssh/id_rsa dx1.diepxuan.com:public_html" | sudo tee /etc/auto.master.d/dxvn.sshfs

    # use /etc/fstab
    # sudo mkdir -p /dxvn/luong
    # ductn@dx1.diepxuan.com:/home/ductn/public_html  /dxvn/luong  fuse.sshfs  defaults  0  0
fi

if [ $_IS_SUDOER = "on" ] || [ "$(whoami)" = "ductn" ]; then
    echo "ductn ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/90-users >/dev/null
fi

if [ "$(whoami)" = "ductn" ]; then
    ./ductn_hosts remove 10.8.0.1  dx2
    ./ductn_hosts remove 10.8.0.1 dx1
    ./ductn_hosts remove 10.8.0.3  dx3
    ./ductn_hosts add 10.8.0.10 vn11
    ./ductn_hosts add 10.8.0.11 mg15
fi
