#!/usr/bin/env bash
#!/bin/bash

dpkg -s ductn 2>/dev/null | grep 'install ok installed' >/dev/null 2>&1
if [ $? != 0 ]; then
    sudo add-apt-repository ppa:caothu91/ppa
    sudo apt install ductn -y --purge --auto-remove
else
    /usr/bin/ductn "$*"
fi
