#!/bin/bash

cat /var/www/base/bash/git/.gitignore >~/.gitignore
chmod 644 ~/.gitignore

# global gitignore
git config --global core.excludesfile ~/.gitignore

# setting
git config --global user.name "Tran Ngoc Duc"
git config --global user.email "caothu91@gmail.com"

# alias
git config --global alias.plog "log --graph --pretty=format:'%h -%d %s %n' --abbrev-commit --date=relative --branches"

# push
git config --global push.default simple

# file mode
git config --global core.fileMode false

# line endings
git config --global core.autocrlf false
git config --global core.eol lf

# Cleanup
git config --global gc.auto 0

# remote server
git config --global receive.denyCurrentBranch updateInstead
