#!/usr/bin/env bash
#!/bin/bash

_MYSQL_REPLICATE=""
_MYSQL_REPLICATE_TOOGLE=""
_MYSQL_REPLICATE_TOOGLE=""
_MYSQL_REPLICATE_HOST=0

_DEBUG=0
_BASEDIR="/var/www/base"
_BASHDIR="$_BASEDIR/bash"
_LIBDIR="$_BASEDIR/lib"
_BINDIR="$_BASHDIR/bin"

. $_BASHDIR/hosts
. $_BASHDIR/ssh
. $_BASHDIR/ssl
. $_BASHDIR/sys
# . $_BASHDIR/vpn/pptp
. $_BASHDIR/httpd
. $_BASHDIR/log
. $_BASHDIR/git
. $_BASHDIR/wsl
. $_BASHDIR/swap
. $_BASHDIR/ddns
. $_BASHDIR/dns
. $_BASHDIR/php
. $_BASHDIR/composer
. $_BASHDIR/ufw
. $_BASHDIR/user
. $_BINDIR/cron.sh
. $_BINDIR/ip.sh
. $_BINDIR/cloudflare.sh
. $_BINDIR/host.sh
. $_BINDIR/mysql
. $_BINDIR/mssql
. $_BINDIR/mssql_php
. $_BINDIR/sys.ad.sh
. $_BINDIR/version.sh

if [[ ! -z ${@+x} ]]; then
    "--$@"
    exit 0
else
    --ip:domain

    # printf "%s " "Press enter to continue"
    # read ans

    read -t 5 -n 1 -s -r -p "Press any key to continue"
    exit 0
fi

exit 0
