#!/bin/bash

_certbot_install() {
  sudo apt install software-properties-common -y --purge --auto-remove
  # sudo add-apt-repository universe
  sudo add-apt-repository ppa:certbot/certbot
  sudo apt update
  sudo apt install -y certbot python-certbot-apache python-pip --purge --auto-remove
  sudo pip install certbot-dns-cloudflare
}

if [[ $1 = "install" ]]; then
    _certbot_install
fi

#sudo certbot certonly --apache \
#  --expand \
#  --no-redirect \
#  --keep-until-expiring \
#  --break-my-certs \
#  --pre-hook /var/www/base/bash/certbot/authenticator.sh \
#  -m caothu91@gmail.com \
#  --server https://acme-v02.api.letsencrypt.org/directory

_certbot() {

  chmod 600 /var/www/base/bash/certbot/cloudflare.ini

  sudo certbot certonly \
    --expand \
    --keep-until-expiring \
    --dns-cloudflare \
    --dns-cloudflare-credentials /var/www/base/bash/certbot/cloudflare.ini \
    --agree-tos \
    --email caothu91@gmail.com \
    --eff-email \
    -d $1
}

#_certbot solzatech.com,www.solzatech.com
_certbot diepxuan.com,www.diepxuan.com,luong.diepxuan.com,insider.diepxuan.com,pma.diepxuan.com,blog.diepxuan.com,cloud.diepxuan.com,work.diepxuan.com,dns.diepxuan.com

sudo service apache2 restart

#  sudo cat /etc/letsencrypt/live/mail.diepxuan.com/fullchain.pem | ssh server3.diepxuan.com "sudo tee /etc/letsencrypt/live/mail.diepxuan.com/fullchain.pem"
#  sudo cat /etc/letsencrypt/live/mail.diepxuan.com/privkey.pem | ssh server3.diepxuan.com "sudo tee /etc/letsencrypt/live/mail.diepxuan.com/privkey.pem"

sudo cat /etc/letsencrypt/live/diepxuan.com/cert.pem | ssh dx3.diepxuan.com "sudo tee /etc/letsencrypt/live/diepxuan.com/cert.pem"
sudo cat /etc/letsencrypt/live/diepxuan.com/chain.pem | ssh dx3.diepxuan.com "sudo tee /etc/letsencrypt/live/diepxuan.com/chain.pem"
sudo cat /etc/letsencrypt/live/diepxuan.com/fullchain.pem | ssh dx3.diepxuan.com "sudo tee /etc/letsencrypt/live/diepxuan.com/fullchain.pem"
sudo cat /etc/letsencrypt/live/diepxuan.com/privkey.pem | ssh dx3.diepxuan.com "sudo tee /etc/letsencrypt/live/diepxuan.com/privkey.pem"
