#!/usr/bin/env bash
#!/bin/bash

. $_BASHDIR/environment

. $_BASHDIR/hosts
# . $_BASHDIR/ssh
. $_BASHDIR/ssl
. $_BASHDIR/sys
# . $_BASHDIR/vpn/pptp
. $_BASHDIR/httpd
. $_BASHDIR/log
. $_BASHDIR/git
. $_BASHDIR/wsl
. $_BASHDIR/swap
. $_BASHDIR/ddns
. $_BASHDIR/dns
. $_BASHDIR/php
. $_BASHDIR/composer
. $_BASHDIR/ufw
. $_BASHDIR/user

. $_BINDIR/mysql
. $_BINDIR/mssql
. $_BINDIR/mssql_php

--init() {
    mkdir -p $DIRTMP
    sudo chmod 777 -R $DIRTMP
}

--import() {
    if [ -d $_BINDIR ]; then
        for f in $_BINDIR/*.sh; do
            if [[ -f $f ]]; then
                source $f
                # test -x $f && source $f
                # echo $f
            fi
        done
    fi
}

--install() {

    if [[ "$(--sys:apt:check jq)" -eq 1 ]]; then
        --sys:apt:install jq
    fi
}

--init
--import
--install
