#!/usr/bin/env bash
#!/bin/bash

_BASEDIR="/var/www/base"
_BASHDIR="$_BASEDIR/bash"

--sys:ufw() {
    --ufw:cleanup
}

--sys:hosts() {
    --hosts:add $(--ddns:getip dxvnmg15.diepxuan.com) mg15
    --hosts:add $(--ddns:getip dx3.diepxuan.com) dx3
}

--ufw:cleanup() {
    TYPE=$1

    DDNS_IPS=()
    for domain in "${DDNS_DOMAINS[@]}"; do
        IP="$(--ddns:getip $domain)"
        DDNS_IPS+=($IP)
    done

    sudo ufw status numbered | sed -n '/Anywhere[[:space:]]\+ALLOW IN[[:space:]]\+/p' | while read line; do
        line="$(echo "$line" | sed -r 's/[[:space:]*[0-9]+][[:space:]]Anywhere[[:space:]]+ALLOW IN[[:space:]]+//g')"
        line="$(echo "$line" | sed -r 's/\/tcp//g')"

        if [[ " ${DDNS_IPS[*]} " =~ " ${line} " ]]; then
            [[ $TYPE =~ "cmd" ]] && echo "Exist $line"
        else
            sudo ufw delete allow proto tcp from "$line"
            [[ $TYPE =~ "cmd" ]] && echo "Remove $line"
        fi

        # local match=false

        # for domain in "${DDNS_DOMAINS[@]}"; do
        #     [[ " $(--ddns:getip $domain) " =~ " ${value} " ]] && match=true
        # done

        # [[ $match ]] && echo $line
    done

    --ddns:update
}

--sys:init() {
    _IS_SERVER="off"
    --server() {
        _IS_SERVER="on"
    }

    _IS_SUDOER="off"
    --admin() {
        _IS_SUDOER="on"
    }

    $@

    echo ". $_BASHDIR/.bash_aliases" >~/.bash_aliases

    rm ~/.vimrc
    ln $_BASHDIR/.vimrc ~/.vimrc
    ln -s $_BASHDIR/.vimrc ~/.vimrc

    chmod 644 ~/.bash_aliases
    chmod 644 ~/.vimrc
    sed -i 's/.*force_color_prompt\=.*/force_color_prompt=yes/' ~/.bashrc

    if [ "$(whoami)" = "ductn" ]; then
        chmod +x $_BASHDIR/*
        sudo timedatectl set-timezone Asia/Ho_Chi_Minh
        sudo cp $_BASHDIR/ductn /usr/local/bin/ductn
        sudo chown root:root /usr/local/bin/ductn
    fi

    $_BASHDIR/ductn git -i

    if [[ $_IS_SERVER = "on" ]]; then
        $_BASHDIR/ductn cronjob -i
        $_BASHDIR/ductn httpd --config
        $_BASHDIR/ductn ssh -i
        # ./bash/ductn --update allowip
        # else
        # sudo mkdir -p /etc/auto.master.d/
        # echo "/dxvn /etc/auto.master.d/dxvn.sshfs --timeout=30" | sudo tee /etc/auto.master.d/dxvn.autofs
        # echo "luong -fstype=nfs,rw,soft,intr,IdentityFile=/home/ductn/.ssh/id_rsa dx1.diepxuan.com:public_html" | sudo tee /etc/auto.master.d/dxvn.sshfs

        # use /etc/fstab
        # sudo mkdir -p /dxvn/luong
        # ductn@dx1.diepxuan.com:/home/ductn/public_html  /dxvn/luong  fuse.sshfs  defaults  0  0
    fi

    if [ $_IS_SUDOER = "on" ] || [ "$(whoami)" = "ductn" ]; then
        echo "ductn ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/90-users >/dev/null
    fi

    if [ "$(whoami)" = "ductn" ]; then
        # $_BASHDIR/ductn hosts remove 10.8.0.3 dx2
        # $_BASHDIR/ductn hosts remove 10.8.0.2 dx1
        # $_BASHDIR/ductn hosts remove 10.8.0.1 dx3
        # $_BASHDIR/ductn hosts remove 10.8.0.10 vn11
        # $_BASHDIR/ductn hosts remove 10.8.0.11 mg15
        # $_BASHDIR/ductn hosts remove 10.8.0.12 mg15kt

        $_BASHDIR/ductn hosts remove 10.8.0.2 dx1.diepxuan.com
        $_BASHDIR/ductn hosts remove 10.8.0.3 dx2.diepxuan.com
        $_BASHDIR/ductn hosts remove 10.8.0.1 dx3.diepxuan.com
    fi

    source ~/.bashrc
}
