#!/usr/bin/env bash
#!/bin/bash

--sys:ufw() {
    --sys:ufw:cleanup
    --sys:ufw:allow
    # --sys:hosts
}

--sys:hosts() {
    --hosts:add $(--ddns:getip dxvnmg15.diepxuan.com) mg15
    --hosts:add $(--ddns:getip dx3.diepxuan.com) dx3
}

--sys:ufw:cleanup() {
    --ufw:cleanup
}

--sys:ufw:_allow() {
    if [ "$(whoami)" = "ductn" ]; then
        # sudo ufw allow proto tcp from "$(--ddns:getip $@)" to any port 1433
        sudo ufw allow from "$(--ddns:getip $@)"
    fi
}

--sys:ufw:allow() {
    for domain in "${DDNS_DOMAINS[@]}"; do
        # echo $domain
        --sys:ufw:_allow $domain
    done
}

--sys:init() {
    _IS_SERVER="off"
    --server() {
        _IS_SERVER="on"
    }

    _IS_SUDOER="off"
    --admin() {
        _IS_SUDOER="on"
    }

    echo ". $_BASHDIR/.bash_aliases" >~/.bash_aliases

    rm ~/.vimrc
    ln $_BASHDIR/.vimrc ~/.vimrc
    chmod 644 ~/.bash_aliases
    chmod 644 ~/.vimrc
    sed -i 's/.*force_color_prompt\=.*/force_color_prompt=yes/' ~/.bashrc

    if [ "$(whoami)" = "ductn" ]; then
        chmod +x $_BASHDIR/*
        sudo timedatectl set-timezone Asia/Ho_Chi_Minh

        echo ". $_BASHDIR/ductn" | sudo tee /usr/local/bin/ductn >/dev/null
        sudo chown root:root /usr/local/bin/ductn
        sudo chmod +x /usr/local/bin/ductn
    fi

    --git:configure

    if [[ $_IS_SERVER = "on" ]]; then
        --cron:install
        --httpd:config
        --ssh:install
        # ./bash/ductn --update allowip
        # else
        # sudo mkdir -p /etc/auto.master.d/
        # echo "/dxvn /etc/auto.master.d/dxvn.sshfs --timeout=30" | sudo tee /etc/auto.master.d/dxvn.autofs
        # echo "luong -fstype=nfs,rw,soft,intr,IdentityFile=/home/ductn/.ssh/id_rsa dx1.diepxuan.com:public_html" | sudo tee /etc/auto.master.d/dxvn.sshfs

        # use /etc/fstab
        # sudo mkdir -p /dxvn/luong
        # ductn@dx1.diepxuan.com:/home/ductn/public_html  /dxvn/luong  fuse.sshfs  defaults  0  0
    fi

    if [ $_IS_SUDOER = "on" ] || [ "$(whoami)" = "ductn" ]; then
        echo "ductn ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/90-users >/dev/null
    fi

    # if [ "$(whoami)" = "ductn" ]; then
    # $_BASHDIR/ductn hosts remove 10.8.0.3 dx2
    # $_BASHDIR/ductn hosts remove 10.8.0.2 dx1
    # $_BASHDIR/ductn hosts remove 10.8.0.1 dx3
    # $_BASHDIR/ductn hosts remove 10.8.0.10 vn11
    # $_BASHDIR/ductn hosts remove 10.8.0.11 mg15
    # $_BASHDIR/ductn hosts remove 10.8.0.12 mg15kt

    # $_BASHDIR/ductn hosts remove 10.8.0.2 dx1.diepxuan.com
    # $_BASHDIR/ductn hosts remove 10.8.0.3 dx2.diepxuan.com
    # $_BASHDIR/ductn hosts remove 10.8.0.1 dx3.diepxuan.com
    # fi

    source ~/.bashrc
    source ~/.bash_aliases
}

--sys:selfupdate() {
    if [[ "$(--version:islatest)" -eq 1 ]]; then
        cd "$_BASEDIR"
        git fetch -ap
        git reset --hard origin/master
    fi
}

--selfupdate() {
    --sys:selfupdate
    --sys:init
}

--self-update() {
    --selfupdate
}

--sys:apt:fix() {
    --apt:fix
}

. $_BASHDIR/sys.sysctl
