#!/usr/bin/env bash
#!/bin/bash

_BASEDIR="/var/www/base"
_BASHDIR="$_BASEDIR/bash"
export PATH="$PATH:$_BASEDIR/bash"

--ufw:geoip:install() {
    sudo apt install curl unzip perl -y --purge --auto-remove
    sudo apt install xtables-addons-common -y --purge --auto-remove
    sudo apt install libtext-csv-xs-perl libmoosex-types-netaddr-ip-perl -y --purge --auto-remove
}

--ufw:geoip:update() {
    MON=$(date +"%m")
    YR=$(date +"%Y")
    sudo mkdir -p /usr/share/xt_geoip
    sudo chmod +x /usr/lib/xtables-addons/*

    sudo rm /usr/share/xt_geoip/dbip-country-lite.csv
    (cd /usr/share/xt_geoip && sudo /usr/lib/xtables-addons/xt_geoip_dl)

    # sudo wget https://download.db-ip.com/free/dbip-country-lite-${YR}-${MON}.csv.gz -O /usr/share/xt_geoip/dbip-country-lite.csv.gz
    # sudo gunzip /usr/share/xt_geoip/dbip-country-lite.csv.gz

    sudo /usr/lib/xtables-addons/xt_geoip_build -D /usr/share/xt_geoip/ -S /usr/share/xt_geoip/
    sudo rm /usr/share/xt_geoip/dbip-country-lite.csv
}

--ufw:geoip:configuration() {
    --ufw:geoip:update
    sudo modprobe xt_geoip
    # lsmod | grep ^xt_geoip
    # iptables -m geoip -h

    ##########################
    # /etc/ufw/before.rules  #
    # /etc/ufw/before6.rules #
    ##########################
    # GeoIp
    # -A ufw-before-input -m geoip ! --src-cc VN -j ACCEPT
}
