#!/bin/bash

service(){
    # Web Server
    if [[ ! "$(sudo /usr/sbin/service apache2 status)" =~ "start/running" ]]; then
        sudo /usr/sbin/service apache2 start
    fi
    if [[ ! "$(sudo /usr/sbin/service mysql status)" =~ "start/running" ]]; then
        sudo rm -rf /swapfile
        sudo fallocate -l 5G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        sudo /usr/sbin/service mysql start
    fi

    # Mysql Cluster
    # if [[ ! "$(sudo /usr/sbin/service ndb_mgmd status)" =~ "start/running" ]]; then
    #     sudo killall ndb_mgmd
    #     sudo rm -rf /usr/mysql-cluster/*
    #     sudo /usr/sbin/service ndb_mgmd start

    #     if [[ ! "$(sudo /usr/sbin/service ndbd status)" =~ "start/running" ]]; then
    #         sudo killall ndbd
    #         sudo /usr/sbin/service ndbd start
    #     fi
    # fi
}

update(){

    updateallowip(){

        allowdomain(){

            getip(){
                host $@ | cut -f4 -d' '
            }

            sudo ufw allow proto tcp from "$(getip $@)" to any port 1433
        }

        allowdomain dxvnkthd.ddns.net
        allowdomain dxvnk113.ddns.net
        allowdomain dxvnkkcn.ddns.net
        allowdomain mg15vincom.ddns.net
    }

    $@

}

$@
